###1
GET https://timeapi.io/api/health/check
Accept: application/json

###2
GET https://timeapi.io/api/time/current/zone?timeZone=Europe%2FBerlin
Accept: application/json

###3
GET https://timeapi.io/api/time/current/ip?ipAddress=79.227.77.155
Accept: application/json

###4
GET https://timeapi.io/api/conversion/dayoftheweek/2025-07-07

###5
POST https://timeapi.io/api/conversion/translate
Content-Type: application/json
{
  "dateTime": "2025-07-07T14:41:34",
  "languageCode": "de"
}
